name: my_599_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - fiona
  - geopandas
  - scikit-learn
  - scikit-image
  - rasterio
  - matplotlib
  - shapely
  - pip
  - pip:
      - tqdm
